version: '3.8'
services:
  webapp.student_list:
    container_name: webpage
    depends_on:
      - pozos_api
    image: php:apache
    environment:
      - USERNAME=toto
      - PASSWORD=python
    ports:
      - "80:80"
    volumes:
      - ./www/:var/www/html/
    networks:
      - pozos_network
  
  pozos_api:
    image: api-pozos:1
    container_name: pozos_api
    volumes: 
      - './simple_api/:/data/'
    networks:
      - pozos_network

  networks:
    pozos_network:
      name: pozos_network
      driver: bridge



